Update config.yml
added dump report to kvdb

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -202,6 +202,30 @@ jobs:
               ansible-playbook -i inventory.txt configure-server.yml
       # Here's where you will add some code to rollback on failure    
 
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+            exit 1
+      - run:
+          name: Send migration status to kvdb.io 
+          command: |   
+              if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+              then
+                  # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+                  curl https://kvdb.io/Y486qWLJa2eJcBFWzwFR7K/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              fi
+     # Here's where you will add some code to rollback on failure     
+
 workflows:
   default:
     jobs:
