Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -347,6 +347,40 @@ jobs:
           cfname: "be-stack-${CIRCLE_WORKFLOW_ID:0:7}"
       - destroy-environment-onfail:
           cfname: "fe-stack-${CIRCLE_WORKFLOW_ID:0:7}"
+# With rollback - circleci/node:9.11
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:9.11
+    steps:
+      # Checkout code from git
+      - checkout
+      - add_ssh_keys:
+          fingerprint: ["f0:c2:1b:03:ba:ff:3e:9d:91:82:eb:c5:c1:c7:17:9b"]
+      - run:
+          name: Run migrations
+          become: true
+          command: |
+            cd backend
+            npm install
+            npm run migrations > backend/src/migrations/migrationResults.txt
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if [ $(cat backend/src/migrations/migrationResults.txt | grep "has been executed successfully" | wc -l) = 3 ]
+            then
+            curl -H "Content-Type: text/plain" -H "token: 790263bd-4df2-4649-b0b4-96321cdce047" --request PUT --data "successful" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            else
+            curl -H "Content-Type: text/plain" -H "token: 790263bd-4df2-4649-b0b4-96321cdce047" --request PUT --data "error" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            exit 1
+            fi
+     # Here's where you will add some code to rollback on failure
+      - aws-cli/install
+      - destroy-environment-onfail:
+          cfname: "be-stack-${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment-onfail:
+          cfname: "fe-stack-${CIRCLE_WORKFLOW_ID:0:7}"
+
 # with rollback - amazon/aws-cli
   deploy-frontend:
     docker:
@@ -379,37 +413,7 @@ jobs:
       - destroy-environment-onfail:
           cfname: "fe-stack-${CIRCLE_WORKFLOW_ID:0:7}"
 
-# With rollback - circleci/node:9.11
-  run-migrations:
-    docker:
-      # Docker image here that supports NodeJS
-      - image: circleci/node:9.11
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Run migrations
-          become: true
-          command: |
-            cd backend
-            npm install
-            npm run migrations > backend/src/migrations/migrationResults.txt
-      - run:
-          name: Send migration results to memstash
-          command: |
-            if [ $(cat backend/src/migrations/migrationResults.txt | grep "has been executed successfully" | wc -l) = 3 ]
-            then
-            curl -H "Content-Type: text/plain" -H "token: 790263bd-4df2-4649-b0b4-96321cdce047" --request PUT --data "successful" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-            else
-            curl -H "Content-Type: text/plain" -H "token: 790263bd-4df2-4649-b0b4-96321cdce047" --request PUT --data "error" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-            exit 1
-            fi
-     # Here's where you will add some code to rollback on failure
-      - aws-cli/install
-      - destroy-environment-onfail:
-          cfname: "be-stack-${CIRCLE_WORKFLOW_ID:0:7}"
-      - destroy-environment-onfail:
-          cfname: "fe-stack-${CIRCLE_WORKFLOW_ID:0:7}"
+
 #curl -H "token: 790263bd-4df2-4649-b0b4-96321cdce047" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
 #exit 1
   print_workspace:
